/**
 * Slugs that are 301-redirected to canonical posts.
 * These should be excluded from sitemap, RSS/Atom feeds, and pre-rendering.
 * Keep in sync with vercel.json redirects.
 */
module.exports = new Set([
  'why-petrolatum-free-lip-care-matters-for-professionals',
  'beeswax-vs-petroleum-jelly-the-best-lip-care-choice',
  'jesse-a-eisenbalm-a-tactile-grounding-tool-for-digital-fatigue',
  'neurocosmetic-lip-balm-grounding-ritual-for-digital-wellness',
  'digital-fatigue-recovery-ritual-with-jesse-a-eisenbalm',
  'beeswax-moisturiser-benefits-for-digital-wellness',
  'ceramides-lip-barrier-enhancing-lip-health-with-beeswax',
  'ceramide-lip-balm-benefits-for-digital-wellness',
  'bio-compatible-lip-occlusion-with-jesse-a-eisenbalm',
  'beeswax-barrier-repair-a-natural-solution-for-lips',
  'mindful-gift-for-executives-jesse-a-eisenbalm-lip-balm',
  'knowledge-worker-wellness-mindful-skincare-with-jesse-a-eisenbalm',
  'executive-grounding-ritual-with-jesse-a-eisenbalm',
  'limited-edition-lip-balm-a-mindful-gift-for-executives',
  'active-ingredients-in-lip-balm-a-professionals-guide',
  'non-toxic-lip-balm-ingredients-for-mindful-lip-care',
  'ingredient-purity-in-natural-chapstick-alternatives',
  'sourcing-pure-beeswax-a-commitment-to-ingredient-transparency',
  'discover-jesse-a-eisenbalms-limited-edition-skincare',
  'discover-premium-lip-balm-for-sale',
  'discover-the-best-lip-balm-for-mindful-living',
  'discover-serenity-with-premium-lip-balm',
  'mindful-skincare-routine-intentional-lip-care-philosophy',
  'skincare-as-meditation-a-mindful-ritual-with-beeswax-lip-balm',
  'mindfulness-morning-routine-with-lip-care-rituals',
  'the-art-of-slow-beauty-rituals-mindful-lip-care',
  'the-art-of-slow-beauty-rituals-embrace-mindful-lip-care',
  'analog-ritual-in-the-digital-age-lip-balm-application',
  'analog-rituals-in-the-digital-age-a-path-to-mindfulness',
  'quality-over-quantity-skincare-intentional-choices-for-mindful-living',
  'embrace-intentional-purchasing-through-skincare-choices',
  'handmade-artisan-lip-balm-a-mindful-digital-wellness-ritual',
  'the-timeless-allure-of-artisan-beauty-products',
  'exploring-beeswax-properties-for-skin-benefits',
  'tewl-lip-care-how-beeswax-protects-and-nourishes',
  'charity-lip-balm-jesse-a-eisenbalms-philanthropic-mission',
  'crafting-an-intentional-daily-ritual-for-digital-professionals',
  'lip-care-for-office-workers-a-mindful-approach',
  'why-lips-dry-out-faster-and-how-to-protect-them',
]);
